#%RAML 1.0
title: Insurance Application API 
version: v1.0.0
mediaType: application/json

/accounts:
  get:
    description: Get list of bank accounts
    responses:
      200:
        body:
          application/json:
            example: !include /Examples/Account.json
              
  post:
    description: Create a new bank account
    responses:
      201:
        body:
          application/json:
            example: !include /Examples/Account.json
  /{accountId}:
    get:
      description: Get specific customer details
      responses:
        200:
          body:
            application/json:
              example: !include /Examples/getById.json
/transactions:
  get:
    description: Get all Transaction
    queryParameters:
      accountId:
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            example: !include /Examples/transaction.json
/cards:
  get:
    description: Get all Cards
    responses:
      200:
        body:
          application/json:
            example: !include /Examples/Card.json

  post:
    description: Issue a new Card
    body:
      application/json:
        example: |
          {
            "id": "string",
            "accountId": "string",
            "cardType": "string",
            "expiryDate": "2025-12-31"
          }
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "Message": "New Card Issued"
              }
